Repository Hochfrequenz/fristenkalender-frontend, pull requests merged in 2025-02, with the labels that each got.

#94 refactor: remove obsolete "Loading" screen from landing page
  src/routes/+layout.svelte
Labels: refactor

#98 fix: use correct custom color for landing page horizontal rule
  src/routes/+page.svelte
  tailwind.config.js
Labels: fix

#102 chore: use companystylesheet `herz.svg` in `icon-heart` component
  src/lib/components/shared/icon-heart.svelte
Labels: chore

#104 chore: remove obsolete `icon-login` component and auth button
  src/lib/components/index.ts
  src/lib/components/shared/auth-button.svelte
  src/lib/components/shared/icon-login.svelte
Labels: chore

#108 chore: use `secondary` background color for table component
  src/lib/components/features/calendar-table.svelte
  src/lib/components/features/download-button.svelte
  src/lib/components/features/glossary-toggle.svelte
  src/routes/fristenkalender/+page.svelte
Labels: chore

#109 feat: add Github link to footer
  src/lib/components/shared/footer.svelte
Labels: feature

#111 fix: reduce HF symbol width to `23 px`
  src/lib/components/shared/header.svelte
  src/lib/components/shared/icon-login.svelte
Labels: fix

#112 fix: change custom color for table header background to `secondary`
  src/lib/components/features/calendar-table.svelte
Labels: fix

#127 fix: use corporate design color for AHB button
  src/lib/components/shared/footer-tools.svelte
  tailwind.config.js
Labels: fix

#128 chore: add scrollbar to calendar table component
  package.json
  src/lib/components/features/calendar-table.svelte
  src/routes/fristenkalender/+page.svelte
  tailwind.config.js
Labels: chore

#135 fix: remove tangibility from landing page box
  src/routes/+page.svelte
Labels: fix
