Repository Hochfrequenz/fristenkalender-frontend, pull requests merged in 2025-01, with the labels that each got.

#35 chore: replace CORS proxy using direct fetch
  src/lib/components/features/calendar-table.svelte
  src/lib/components/features/download-button.svelte
Labels: chore

#36 chore: remove caching as data is now fetched instantly anyway
  src/lib/components/features/calendar-table.svelte
Labels: chore

#37 chore: remove proxy service to trigger `ics` download instantly
  src/lib/services/download-ics.ts
Labels: chore

#38 ci: set auth0 client IDs for stage/prod in deployment workflows
  .github/workflows/azure-static-web-apps-brave-ocean-076b69903.yml
  .github/workflows/azure-static-web-apps-icy-stone-001be1b03.yml
  src/auth/auth_config.ts
Labels: CI/CD

#40 chore: add fristenkalender pdfs for 2023, 2024 and 2025
  static/fristenkalender/2023_hochfrequenz_fristenkalender.pdf
  static/fristenkalender/2024_hochfrequenz_fristenkalender.pdf
  static/fristenkalender/2025_hochfrequenz_fristenkalender.pdf
Labels: chore

#41 chore: add tailwind spinner component for `isLoading` state of table
  src/lib/components/features/calendar-table.svelte
  src/lib/components/features/download-button.svelte
  src/lib/components/index.ts
  src/lib/components/shared/icon-spinner.svelte
Labels: chore

#47 fix: update fristenkalender 2025
  static/fristenkalender/2025_hochfrequenz_fristenkalender.pdf
Labels: fix

#48 feat: add version endpoint
  .github/workflows/azure-static-web-apps-brave-ocean-076b69903.yml
  .github/workflows/azure-static-web-apps-icy-stone-001be1b03.yml
  src/lib/components/shared/footer.svelte
  src/routes/+layout.svelte
  src/routes/version/+page.svelte
  static/version.json
Labels: feature

#49 chore: hide table scrollbar
  package-lock.json
  package.json
  src/lib/components/features/calendar-table.svelte
  tailwind.config.js
Labels: chore

#60 chore: remove the login button of the landing page
  src/routes/+page.svelte
Labels: chore

#61 chore: apply corporate design
  package-lock.json
  src/lib/components/features/calendar-month-select.svelte
  src/lib/components/features/calendar-table.svelte
  src/lib/components/features/calendar-type-select.svelte
  src/lib/components/features/calendar-year-select.svelte
  src/lib/components/features/download-button.svelte
  src/lib/components/features/glossary-toggle.svelte
  src/lib/components/shared/auth-button.svelte
  src/lib/components/shared/footer.svelte
  src/lib/components/shared/header.svelte
  src/routes/+page.svelte
  tailwind.config.js
Labels: chore

#62 fix: adjust glossary positioning and z layering
  src/lib/components/features/glossary-toggle.svelte
  src/lib/components/shared/footer.svelte
  src/lib/components/shared/header.svelte
Labels: fix

#63 feat: add footer for HF tools
  src/lib/components/features/calendar-month-select.svelte
  src/lib/components/features/calendar-table.svelte
  src/lib/components/features/calendar-type-select.svelte
  src/lib/components/features/calendar-year-select.svelte
  src/lib/components/features/download-button.svelte
  src/lib/components/features/glossary-toggle.svelte
  src/lib/components/index.ts
  src/lib/components/shared/footer-tools.svelte
  src/lib/components/shared/footer.svelte
  src/lib/components/shared/header.svelte
  src/lib/components/shared/icon-spinner.svelte
  src/routes/+page.svelte
  src/routes/fristenkalender/+layout.svelte
  src/routes/fristenkalender/+page.svelte
  tailwind.config.js
Labels: feature

#64 fix: reduce button padding inside second footer
  src/lib/components/shared/footer-tools.svelte
Labels: fix
